spring.application.name=puntooficio

# MySQL
spring.datasource.url=jdbc:mysql://localhost:3306/puntooficio
spring.datasource.username=root
spring.datasource.password=Efracruz10!
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
spring.jpa.hibernate.ddl-auto=update
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect

# Servidor
server.port=8080

# JWT
jwt.secret=5a7134743777217a25432a462d4a614e645267556b58703273357638792f423f
jwt.expiration=86400000